//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIPNET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIPNET.Resources.strings-fr", typeof(strings_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situation inconnue général.
        /// </summary>
        internal static string GeneralStatus_Unknown {
            get {
                return ResourceManager.GetString("GeneralStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service a été réalisée avec succès par l&apos;objet spécifié.
        /// </summary>
        internal static string GeneralStatusDesc_0x00 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection related service failed along the connection path..
        /// </summary>
        internal static string GeneralStatusDesc_0x01 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un service de connexion liés échoué le long du chemin de connexion..
        /// </summary>
        internal static string GeneralStatusDesc_0x02 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un paramètre associé à la demande n&apos;était pas valable. Ce code est utilisé quand un paramètre ne répond pas aux exigences de cette spécification et / ou les exigences définies dans une spécification de l&apos;objet Application..
        /// </summary>
        internal static string GeneralStatusDesc_0x03 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;identifiant segment de chemin ou de la syntaxe du segment n&apos;a pas été comprise par le nœud de traitement. Chemin de traitement doit s&apos;arrêter quand une erreur est rencontrée segment de chemin..
        /// </summary>
        internal static string GeneralStatusDesc_0x04 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le chemin est référençant un élément de classe d&apos;objet, par exemple, ou une structure qui n&apos;est pas connu ou n&apos;est pas contenu dans le noeud de traitement. Chemin de traitement doit s&apos;arrêter quand une erreur de destination du sillon inconnu est rencontré..
        /// </summary>
        internal static string GeneralStatusDesc_0x05 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seule une partie des données attendues a été transféré..
        /// </summary>
        internal static string GeneralStatusDesc_0x06 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La connexion de messagerie a été perdu..
        /// </summary>
        internal static string GeneralStatusDesc_0x07 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le service demandé n&apos;a pas été appliqué ou n&apos;a pas été défini pour cette classe d&apos;objet / de l&apos;instance..
        /// </summary>
        internal static string GeneralStatusDesc_0x08 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données d&apos;attribut non valide détecté..
        /// </summary>
        internal static string GeneralStatusDesc_0x09 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un attribut dans la réponse Get_Attribute_List ou Set_Attribute_List a un statut différent de zéro..
        /// </summary>
        internal static string GeneralStatusDesc_0x0A {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;objet est déjà dans le mode / état demandé par le service..
        /// </summary>
        internal static string GeneralStatusDesc_0x0B {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;objet ne peut pas effectuer le service demandé dans son mode actuel / état..
        /// </summary>
        internal static string GeneralStatusDesc_0x0C {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;instance de l&apos;objet demandé à être créée existe déjà..
        /// </summary>
        internal static string GeneralStatusDesc_0x0D {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une demande de modifier un attribut non modifiable a été reçu..
        /// </summary>
        internal static string GeneralStatusDesc_0x0E {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une vérification de permission / privilage échoué..
        /// </summary>
        internal static string GeneralStatusDesc_0x0F {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les appareils en mode courant / Etat interdit l&apos;exécution du service demandé..
        /// </summary>
        internal static string GeneralStatusDesc_0x10 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les données devant être transmises dans la mémoire tampon de réponse est plus grande que le tampon de réponse alloué..
        /// </summary>
        internal static string GeneralStatusDesc_0x11 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le service spécifié une opération qui va se fragmenter une valeur de données primitifs, soit la moitié d&apos;un type de données REAL..
        /// </summary>
        internal static string GeneralStatusDesc_0x12 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le service n&apos;a pas fourni suffisamment de données pour effectuer l&apos;opération spécifiée..
        /// </summary>
        internal static string GeneralStatusDesc_0x13 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;attribut spécifié dans la demande n&apos;est pas supporté..
        /// </summary>
        internal static string GeneralStatusDesc_0x14 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le service fourni plus de données que prévu..
        /// </summary>
        internal static string GeneralStatusDesc_0x15 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;objet spécifié n&apos;existe pas dans le dispositif..
        /// </summary>
        internal static string GeneralStatusDesc_0x16 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La séquence de fragmentation pour ce service n&apos;est pas actuellement actif pour ces données..
        /// </summary>
        internal static string GeneralStatusDesc_0x17 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les données d&apos;attribut de cet objet n&apos;a pas été enregistré avant le service demandé..
        /// </summary>
        internal static string GeneralStatusDesc_0x18 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les données d&apos;attribut de cet objet n&apos;a pas été enregistré en raison d&apos;un échec lors de la tentative..
        /// </summary>
        internal static string GeneralStatusDesc_0x19 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le paquet de demande de service était trop volumineux pour être transmis sur un réseau dans le chemin vers la destination. Le dispositif de routage a été forcée à avorter le service..
        /// </summary>
        internal static string GeneralStatusDesc_0x1A {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le paquet de réponse du service était trop volumineux pour être transmis sur un réseau dans le chemin vers la destination. Le dispositif de routage a été forcée à avorter le service..
        /// </summary>
        internal static string GeneralStatusDesc_0x1B {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le service n&apos;a pas fourni un attribut dans une liste d&apos;attributs qui était nécessaire par le service pour effectuer le comportement demandé..
        /// </summary>
        internal static string GeneralStatusDesc_0x1C {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le service est de retour dans la liste des attributs fournis avec des informations d&apos;état pour les attributs qui ne sont pas valides..
        /// </summary>
        internal static string GeneralStatusDesc_0x1D {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un service incorporés a entraîné une erreur..
        /// </summary>
        internal static string GeneralStatusDesc_0x1E {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite fournisseur spécifique..
        /// </summary>
        internal static string GeneralStatusDesc_0x1F {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un paramètre associé à la demande n&apos;était pas valable..
        /// </summary>
        internal static string GeneralStatusDesc_0x20 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une tentative a été faite d&apos;écrire sur un support non réinscriptible (egWORM disque, PROM) qui a déjà été écrit, ou de modifier une valeur qui ne peut pas être changé une fois établi..
        /// </summary>
        internal static string GeneralStatusDesc_0x21 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une réponse invalide est reçue (par exemple, le code de service n&apos;a pas répondu mach le code de service demande ou message de réponse est plus court que la taille minimale réponse attendue)..
        /// </summary>
        internal static string GeneralStatusDesc_0x22 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le segment clé qui a été inclus comme le premier segment de la voie ne correspond pas au module de destination. Le statut de l&apos;objet spécifique indique quelle partie de la vérification de clés a échoué..
        /// </summary>
        internal static string GeneralStatusDesc_0x25 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La taille de la voie qui a été envoyée avec la demande de service est soit pas assez grande pour permettre à la requête d&apos;être acheminés vers un objet ou trop de données de routage a été inclus..
        /// </summary>
        internal static string GeneralStatusDesc_0x26 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une tentative a été effectuée pour définir un attribut qui n&apos;est pas capable d&apos;être fixé à ce moment..
        /// </summary>
        internal static string GeneralStatusDesc_0x27 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;ID de membre spécifié dans la demande n&apos;existe pas dans la classe spécifiée / instance / Attribute..
        /// </summary>
        internal static string GeneralStatusDesc_0x28 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une demande de modification d&apos;un membre non modifiable a été reçu..
        /// </summary>
        internal static string GeneralStatusDesc_0x29 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette erreur peut être signalée par DeviceNet groupe 2 serveurs uniquement avec 4K ou moins d&apos;espace de code et que la place de Service non supporté, non prise en charge des attributs et des attributs non réglable..
        /// </summary>
        internal static string GeneralStatusDesc_0x2A {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to succès.
        /// </summary>
        internal static string GeneralStatusName_0x00 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to échec de la connexion.
        /// </summary>
        internal static string GeneralStatusName_0x01 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ressource indisponible.
        /// </summary>
        internal static string GeneralStatusName_0x02 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur du paramètre non valide.
        /// </summary>
        internal static string GeneralStatusName_0x03 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur segment de chemin.
        /// </summary>
        internal static string GeneralStatusName_0x04 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Unknown Chemin.
        /// </summary>
        internal static string GeneralStatusName_0x05 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfert partiel.
        /// </summary>
        internal static string GeneralStatusName_0x06 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connexion perdue.
        /// </summary>
        internal static string GeneralStatusName_0x07 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service non supporté.
        /// </summary>
        internal static string GeneralStatusName_0x08 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur d&apos;attribut non valide.
        /// </summary>
        internal static string GeneralStatusName_0x09 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur Liste des attributs.
        /// </summary>
        internal static string GeneralStatusName_0x0A {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déjà en mode demandé / Etat.
        /// </summary>
        internal static string GeneralStatusName_0x0B {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflit Etat Objet.
        /// </summary>
        internal static string GeneralStatusName_0x0C {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objet existant.
        /// </summary>
        internal static string GeneralStatusName_0x0D {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribut non réglable.
        /// </summary>
        internal static string GeneralStatusName_0x0E {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation Privilège.
        /// </summary>
        internal static string GeneralStatusName_0x0F {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflit Etat périphérique.
        /// </summary>
        internal static string GeneralStatusName_0x10 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données de réponse trop gros.
        /// </summary>
        internal static string GeneralStatusName_0x11 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fragmentation de une valeur primitive.
        /// </summary>
        internal static string GeneralStatusName_0x12 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données insuffisantes.
        /// </summary>
        internal static string GeneralStatusName_0x13 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribut non pris en charge.
        /// </summary>
        internal static string GeneralStatusName_0x14 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trop de données.
        /// </summary>
        internal static string GeneralStatusName_0x15 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;objet n&apos;existe pas.
        /// </summary>
        internal static string GeneralStatusName_0x16 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séquence fragmentation des services Pas en cours.
        /// </summary>
        internal static string GeneralStatusName_0x17 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de données d&apos;attribut stockées.
        /// </summary>
        internal static string GeneralStatusName_0x18 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec d&apos;une opération magasin.
        /// </summary>
        internal static string GeneralStatusName_0x19 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec de routage, Packet demande trop grande.
        /// </summary>
        internal static string GeneralStatusName_0x1A {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routage de paquet réponse d&apos;échec, un trop grand.
        /// </summary>
        internal static string GeneralStatusName_0x1B {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données manquantes Attribut Entry List.
        /// </summary>
        internal static string GeneralStatusName_0x1C {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste non valide Valeur d&apos;attribut.
        /// </summary>
        internal static string GeneralStatusName_0x1D {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de services intégrés.
        /// </summary>
        internal static string GeneralStatusName_0x1E {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur Vendor Specific.
        /// </summary>
        internal static string GeneralStatusName_0x1F {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paramètre non valide.
        /// </summary>
        internal static string GeneralStatusName_0x20 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write-Once Valeur ou moyennes déjà écrit.
        /// </summary>
        internal static string GeneralStatusName_0x21 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réponse reçue invalide.
        /// </summary>
        internal static string GeneralStatusName_0x22 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le non-clés dans le chemin.
        /// </summary>
        internal static string GeneralStatusName_0x25 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille Chemin invalide.
        /// </summary>
        internal static string GeneralStatusName_0x26 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribut inattendu dans la liste.
        /// </summary>
        internal static string GeneralStatusName_0x27 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID de membre.
        /// </summary>
        internal static string GeneralStatusName_0x28 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membre non réglable.
        /// </summary>
        internal static string GeneralStatusName_0x29 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe 2 Serveur Seul échec général.
        /// </summary>
        internal static string GeneralStatusName_0x2A {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x2A", resourceCulture);
            }
        }
    }
}
