//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIPNET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIPNET.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown General Status.
        /// </summary>
        internal static string GeneralStatus_Unknown {
            get {
                return ResourceManager.GetString("GeneralStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was successfully performed by the object specified.
        /// </summary>
        internal static string GeneralStatusDesc_0x00 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection related service failed along the connection path..
        /// </summary>
        internal static string GeneralStatusDesc_0x01 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources needed for the object to perform the requested service were unavailable..
        /// </summary>
        internal static string GeneralStatusDesc_0x02 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parameter associated with the request was invalid. This code is used when a parameter does not meet the requirements of this specification and/or the requirements defined in an Application Object Specification..
        /// </summary>
        internal static string GeneralStatusDesc_0x03 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path segment identifier or the segment syntax was not understood by the processing node. Path processing shall stop when a path segment error is encountered..
        /// </summary>
        internal static string GeneralStatusDesc_0x04 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path is referencing an object class, instance, or structure element that is not known or is not contained in the processing node. Path processing shall stop when a path destination unknown error is encountered..
        /// </summary>
        internal static string GeneralStatusDesc_0x05 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only part of the expected data was transferred..
        /// </summary>
        internal static string GeneralStatusDesc_0x06 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The messaging connection was lost..
        /// </summary>
        internal static string GeneralStatusDesc_0x07 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested service was not implemented or was not defined for this Object Class/Instance..
        /// </summary>
        internal static string GeneralStatusDesc_0x08 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attribute data detected..
        /// </summary>
        internal static string GeneralStatusDesc_0x09 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attribute in the Get_Attribute_List or Set_Attribute_List response has a non-zero status..
        /// </summary>
        internal static string GeneralStatusDesc_0x0A {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is already in the mode/state being requested by the service..
        /// </summary>
        internal static string GeneralStatusDesc_0x0B {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object cannot perform the requested service in its current mode/state..
        /// </summary>
        internal static string GeneralStatusDesc_0x0C {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested instance of the object to be created already exists..
        /// </summary>
        internal static string GeneralStatusDesc_0x0D {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to modify a non-modifiable attribute was received..
        /// </summary>
        internal static string GeneralStatusDesc_0x0E {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A permission/privilage check failed..
        /// </summary>
        internal static string GeneralStatusDesc_0x0F {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The devices current mode/state prohibits the execution of the requested service..
        /// </summary>
        internal static string GeneralStatusDesc_0x10 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data to be transmitted in the response buffer is larger than the allocated response buffer..
        /// </summary>
        internal static string GeneralStatusDesc_0x11 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service specified an operation that is going to fragment a primitive data value, i.e. half a REAL data type..
        /// </summary>
        internal static string GeneralStatusDesc_0x12 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service did not supply enough data to perform the specified operation..
        /// </summary>
        internal static string GeneralStatusDesc_0x13 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute specified in the request is not supported..
        /// </summary>
        internal static string GeneralStatusDesc_0x14 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service supplied more data than was expected..
        /// </summary>
        internal static string GeneralStatusDesc_0x15 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object specified does not exist in the device..
        /// </summary>
        internal static string GeneralStatusDesc_0x16 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fragmentation sequence for this service is not currently active for this data..
        /// </summary>
        internal static string GeneralStatusDesc_0x17 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute data of this object was not saved prior to the requested service..
        /// </summary>
        internal static string GeneralStatusDesc_0x18 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute data of this object was not saved due to a failure during the attempt..
        /// </summary>
        internal static string GeneralStatusDesc_0x19 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service request packet was too large for transmission on a network in the path to the destination. The routing device was forced to abort the service..
        /// </summary>
        internal static string GeneralStatusDesc_0x1A {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service response packet was too large for transmission on a network in the path to the destination. The routing device was forced to abort the service..
        /// </summary>
        internal static string GeneralStatusDesc_0x1B {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service did not supply an attribute in a list of attributes that was needed by the service to perform the requested behavior..
        /// </summary>
        internal static string GeneralStatusDesc_0x1C {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is returning the list of attributes supplied with status information for those attributes that were invalid..
        /// </summary>
        internal static string GeneralStatusDesc_0x1D {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An embedded service resulted in an error..
        /// </summary>
        internal static string GeneralStatusDesc_0x1E {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vendor specific error has occurred..
        /// </summary>
        internal static string GeneralStatusDesc_0x1F {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parameter associated with the request was invalid..
        /// </summary>
        internal static string GeneralStatusDesc_0x20 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to write to a write-once medium (e.g.WORM drive, PROM) that has already been written, or to modify a value that cannot be changed once established..
        /// </summary>
        internal static string GeneralStatusDesc_0x21 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid reply is received (e.g. reply service code does not mach the request service code, or reply message is shorter than the minimum expected reply size)..
        /// </summary>
        internal static string GeneralStatusDesc_0x22 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key Segment that was included as the first segment in the path does not match the destination module. The object specific status shall indicate which part of the key check failed..
        /// </summary>
        internal static string GeneralStatusDesc_0x25 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the path which was sent with the Service Request is either not large enough to allow the Request to be routed to an object or too much routing data was included..
        /// </summary>
        internal static string GeneralStatusDesc_0x26 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to set an attribute that is not able to be set at this time..
        /// </summary>
        internal static string GeneralStatusDesc_0x27 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Member ID specified in the request does not exist in the specified Class/Instance/Attribute..
        /// </summary>
        internal static string GeneralStatusDesc_0x28 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request to modify a non-modifiable member was received..
        /// </summary>
        internal static string GeneralStatusDesc_0x29 {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This error may be reported by DeviceNet group 2 only servers with 4K or less code space and only in place of Service Not Supported, Attribute Not Supported, and Attribute Not Settable..
        /// </summary>
        internal static string GeneralStatusDesc_0x2A {
            get {
                return ResourceManager.GetString("GeneralStatusDesc_0x2A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string GeneralStatusName_0x00 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failure.
        /// </summary>
        internal static string GeneralStatusName_0x01 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Unavailable.
        /// </summary>
        internal static string GeneralStatusName_0x02 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter Value.
        /// </summary>
        internal static string GeneralStatusName_0x03 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Segment Error.
        /// </summary>
        internal static string GeneralStatusName_0x04 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Destination Unknown.
        /// </summary>
        internal static string GeneralStatusName_0x05 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Transfer.
        /// </summary>
        internal static string GeneralStatusName_0x06 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Lost.
        /// </summary>
        internal static string GeneralStatusName_0x07 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Not Supported.
        /// </summary>
        internal static string GeneralStatusName_0x08 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Attribute Value.
        /// </summary>
        internal static string GeneralStatusName_0x09 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute List Error.
        /// </summary>
        internal static string GeneralStatusName_0x0A {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in Requested Mode/State.
        /// </summary>
        internal static string GeneralStatusName_0x0B {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object State Conflict.
        /// </summary>
        internal static string GeneralStatusName_0x0C {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Already Exists.
        /// </summary>
        internal static string GeneralStatusName_0x0D {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Not Settable.
        /// </summary>
        internal static string GeneralStatusName_0x0E {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privilage Violation.
        /// </summary>
        internal static string GeneralStatusName_0x0F {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device State Conflict.
        /// </summary>
        internal static string GeneralStatusName_0x10 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply Data Too Large.
        /// </summary>
        internal static string GeneralStatusName_0x11 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragmentation of a Primitive Value.
        /// </summary>
        internal static string GeneralStatusName_0x12 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enough Data.
        /// </summary>
        internal static string GeneralStatusName_0x13 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Not Supported.
        /// </summary>
        internal static string GeneralStatusName_0x14 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Much Data.
        /// </summary>
        internal static string GeneralStatusName_0x15 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Does Not Exist.
        /// </summary>
        internal static string GeneralStatusName_0x16 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Fragmentation Sequence Not In Progress.
        /// </summary>
        internal static string GeneralStatusName_0x17 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Stored Attribute Data.
        /// </summary>
        internal static string GeneralStatusName_0x18 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Operation Failure.
        /// </summary>
        internal static string GeneralStatusName_0x19 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Failure, Request Packet Too Large.
        /// </summary>
        internal static string GeneralStatusName_0x1A {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Failure, Response Packet Too Large.
        /// </summary>
        internal static string GeneralStatusName_0x1B {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Attribute List Entry Data.
        /// </summary>
        internal static string GeneralStatusName_0x1C {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Attribute Value List.
        /// </summary>
        internal static string GeneralStatusName_0x1D {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded Service Error.
        /// </summary>
        internal static string GeneralStatusName_0x1E {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Specific Error.
        /// </summary>
        internal static string GeneralStatusName_0x1F {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter.
        /// </summary>
        internal static string GeneralStatusName_0x20 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write-Once Value or Medium Already Written.
        /// </summary>
        internal static string GeneralStatusName_0x21 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reply Received.
        /// </summary>
        internal static string GeneralStatusName_0x22 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Failure in Path.
        /// </summary>
        internal static string GeneralStatusName_0x25 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Size Invalid.
        /// </summary>
        internal static string GeneralStatusName_0x26 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Attribute in List.
        /// </summary>
        internal static string GeneralStatusName_0x27 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Member ID.
        /// </summary>
        internal static string GeneralStatusName_0x28 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Not Settable.
        /// </summary>
        internal static string GeneralStatusName_0x29 {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 2 Only Server General Failure.
        /// </summary>
        internal static string GeneralStatusName_0x2A {
            get {
                return ResourceManager.GetString("GeneralStatusName_0x2A", resourceCulture);
            }
        }
    }
}
